# WRITTEN BY Shadow Hacker 99 AND MANAGED BY The Wizard 99

name: Shadow Ripping Tools

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste CRD's 2nd Code
        required:& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AQlEd8wA6SEdpjzF7LDf1rccwizVM5g7kGI-1TeaXG4s32NbD4kYEYZN_Vey0rIpNDOdaQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
     

jobs:
  build:
    name: Shadow Ripping Lab Running
    runs-on: windows-latest

    steps:
    - name: Downloading And Installing Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1IWdNFHaewULn7tN8ZOnp3fMfsSSuCxOU&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "ripper.ps1" && ./ripper.ps1
    - name: Starting VirtualMachine 
      run: |
        # CONNECTING WITH VIRTUAL MACHINE
        ${{ inputs.code }} -pin=123456
    - name: VirtualMachine is Running
      run: |
        $i = 360
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
